### ISSUE TITLE
Casting exception when open on device

### ISSUE THREAD

**Issue by kimkha** [emilsjolander/StickyListHeaders#326]
I try to use StickyList on my project, but it always crash when open that list.

My source code:

```java
        // Setup
        adapter = createAdapter(getActivity());
        list_V.setAdapter((AbstractStickyCursorAdapter) adapter);
        if (selectionType == SELECTION_TYPE_NONE)
        {
            create_V = LayoutInflater.from(getActivity()).inflate(R.layout.li_create_new, list_V, false);
            list_V.addFooterView(create_V);
        }
        list_V.setOnItemClickListener(this);
        if (getArguments().getBoolean(ARG_IS_OPEN_DRAWER_LAYOUT, false))
        {
            final int paddingHorizontal = getResources().getDimensionPixelSize(R.dimen.dynamic_margin_drawer_narrow_horizontal);
            list_V.setPadding(paddingHorizontal, list_V.getPaddingTop(), paddingHorizontal, list_V.getPaddingBottom());
        }
        if (selectionType == SELECTION_TYPE_MULTI)
        {
            list_V.setChoiceMode(AbsListView.CHOICE_MODE_MULTIPLE);
            if (savedInstanceState != null)
            {
                final ArrayList<Integer> selectedPositions = savedInstanceState.getIntegerArrayList(STATE_SELECTED_POSITIONS);
                list_V.setTag(selectedPositions);
            }
            else
            {
                final long[] selectedIDs = getArguments().getLongArray(ARG_ITEM_IDS);
                list_V.setTag(selectedIDs);
            }
        }
```

The fragment is https://github.com/kimkha/Finanvita/blob/master/Finanvita/src/main/java/com/kimkha/finance/ui/transactions/TransactionListFragment.java , and it extends https://github.com/kimkha/Finanvita/blob/master/Finanvita/src/main/java/com/kimkha/finance/ui/StickyListFragment.java

This is error log:

```
java.lang.ClassCastException: android.widget.FrameLayout$LayoutParams cannot be cast to android.widget.AbsListView$LayoutParams
            at android.widget.ListView.clearRecycledState(ListView.java:517)
            at android.widget.ListView.resetList(ListView.java:504)
            at android.widget.ListView.layoutChildren(ListView.java:1577)
            at android.widget.AbsListView.onLayout(AbsListView.java:1873)
            at android.view.View.layout(View.java:11444)
            at android.view.ViewGroup.layout(ViewGroup.java:4331)
            at se.emilsjolander.stickylistheaders.StickyListHeadersListView.onLayout(StickyListHeadersListView.java:255)
            at android.view.View.layout(View.java:11444)
            at android.view.ViewGroup.layout(ViewGroup.java:4331)
            at android.widget.FrameLayout.onLayout(FrameLayout.java:443)
            at android.view.View.layout(View.java:11444)
            at android.view.ViewGroup.layout(ViewGroup.java:4331)
            at android.widget.FrameLayout.onLayout(FrameLayout.java:443)
            at android.view.View.layout(View.java:11444)
            at android.view.ViewGroup.layout(ViewGroup.java:4331)
            at android.support.v4.widget.DrawerLayout.onLayout(DrawerLayout.java:690)
            at android.view.View.layout(View.java:11444)
            at android.view.ViewGroup.layout(ViewGroup.java:4331)
            at android.widget.FrameLayout.onLayout(FrameLayout.java:443)
            at android.view.View.layout(View.java:11444)
            at android.view.ViewGroup.layout(ViewGroup.java:4331)
            at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1666)
            at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1524)
            at android.widget.LinearLayout.onLayout(LinearLayout.java:1429)
            at android.view.View.layout(View.java:11444)
            at android.view.ViewGroup.layout(ViewGroup.java:4331)
            at android.widget.FrameLayout.onLayout(FrameLayout.java:443)
            at android.view.View.layout(View.java:11444)
            at android.view.ViewGroup.layout(ViewGroup.java:4331)
            at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1493)
            at android.view.ViewRootImpl.handleMessage(ViewRootImpl.java:2446)
            at android.os.Handler.dispatchMessage(Handler.java:99)
            at android.os.Looper.loop(Looper.java:137)
            at android.app.ActivityThread.main(ActivityThread.java:4448)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:511)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:823)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:590)
            at dalvik.system.NativeStart.main(Native Method)
```

**Comment by kimkha** [comment]
Do you have any idea to solve that problem? Please...

**Comment by durunvo** [comment]
pass null as parent view

create_V = LayoutInflater.from(getActivity()).inflate(R.layout.li_create_new, null, false);

**Comment by kimkha** [comment]
Thanks. It works now.
