### ISSUE TITLE
Error :(

### ISSUE THREAD

**Issue by VizantiecNET** [emilsjolander/StickyListHeaders#373]
I catch error:
**java.lang.IllegalStateException: The content of the adapter has changed but ListView did not receive a notification. Make sure the content of your adapter is not modified from a background thread, but only from the UI thread. [in ListView(-1, class se.emilsjolander.stickylistheaders.WrapperViewList) with Adapter(class se.emilsjolander.stickylistheaders.AdapterWrapper)]
       at android.widget.ListView.layoutChildren(ListView.java:1538)
       at se.emilsjolander.stickylistheaders.WrapperViewList.layoutChildren(WrapperViewList.java:193)
       at android.widget.AbsListView.onLayout(AbsListView.java:2102)
       at android.view.View.layout(View.java:13829)
       at android.view.ViewGroup.layout(ViewGroup.java:4382)
       at se.emilsjolander.stickylistheaders.StickyListHeadersListView.onLayout(StickyListHeadersListView.java:255)
       at android.view.View.layout(View.java:13829)
       at android.view.ViewGroup.layout(ViewGroup.java:4382)
       at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1649)
       at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1507)
       at android.widget.LinearLayout.onLayout(LinearLayout.java:1420)
       at android.view.View.layout(View.java:13829)
       at android.view.ViewGroup.layout(ViewGroup.java:4382)
       at android.widget.RelativeLayout.onLayout(RelativeLayout.java:948)
       at android.view.View.layout(View.java:13829)
       at android.view.ViewGroup.layout(ViewGroup.java:4382)
       at android.widget.RelativeLayout.onLayout(RelativeLayout.java:948)
       at android.view.View.layout(View.java:13829)
       at android.view.ViewGroup.layout(ViewGroup.java:4382)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:448)
       at android.view.View.layout(View.java:13829)
       at android.view.ViewGroup.layout(ViewGroup.java:4382)
       at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1649)
       at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1507)
       at android.widget.LinearLayout.onLayout(LinearLayout.java:1420)
       at android.view.View.layout(View.java:13829)
       at android.view.ViewGroup.layout(ViewGroup.java:4382)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:448)
       at android.view.View.layout(View.java:13829)
       at android.view.ViewGroup.layout(ViewGroup.java:4382)
       at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:1899)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1720)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1027)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:4359)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:725)
       at android.view.Choreographer.doCallbacks(Choreographer.java:555)
       at android.view.Choreographer.doFrame(Choreographer.java:525)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:711)
       at android.os.Handler.handleCallback(Handler.java:615)
       at android.os.Handler.dispatchMessage(Handler.java:92)
       at android.os.Looper.loop(Looper.java:137)
       at android.app.ActivityThread.main(ActivityThread.java:4812)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:511)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:556)
       at dalvik.system.NativeStart.main(NativeStart.java)**

What I do with it?

**Comment by tomcatter** [comment]
well, the log is said you modifed the adapter from a background thread. Android application don't allow to do this. you must do this from  the UI thread. you can use the Handler to modify adapter's data from the Sub Thread.

**Comment by ProfPh** [comment]
Make sure you aren't overriding `getCount()` improperly in your adapter because that is the cause of the error
