### ISSUE TITLE
java.lang.VerifyError:

### ISSUE THREAD

**Issue by kirvis250** [emilsjolander/StickyListHeaders#377]
E/AndroidRuntime﹕ FATAL EXCEPTION: main
    java.lang.VerifyError: se/emilsjolander/stickylistheaders/StickyListHeadersListView
            at java.lang.reflect.Constructor.constructNative(Native Method)
            at java.lang.reflect.Constructor.newInstance(Constructor.java:417)
            at android.view.LayoutInflater.createView(LayoutInflater.java:587)
            at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:687)
            at android.view.LayoutInflater.rInflate(LayoutInflater.java:746)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:489)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:396)

this problem apears on jdk1.8.0_31  on jdk 1.7.0_75 this problem not appears. Problem is that other library, i use, throw same VerifyError on jdk 1.7.0_75 and works fine on jdk 1.8.0_31 . And seems that i can't find any other versions of Java jdk to test out this problem.

**Comment by wangyeming** [comment]
Me too！

**Comment by JianxunRao** [comment]
same issue.
device: XiaoMi/MIUI armeabi-v7a Android 4.4.4,level 19

#1 main
java.lang.VerifyError
se/emilsjolander/stickylistheaders/StickyListHeadersListView
}
1 java.lang.reflect.Constructor.constructNative(Native Method)
2 java.lang.reflect.Constructor.newInstance(Constructor.java:423)
3 android.view.LayoutInflater.createView(LayoutInflater.java:597)
4 android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:699)
5 android.view.LayoutInflater.rInflate(LayoutInflater.java:758)
6 android.view.LayoutInflater.rInflate(LayoutInflater.java:761)
7 android.view.LayoutInflater.inflate(LayoutInflater.java:495)
8 android.view.LayoutInflater.inflate(LayoutInflater.java:400)
9 **net.aimoqi.moqipeddler.fragment.UnfinishedOrderFragment.onCreateView(UnfinishedOrderFragment.java:351)**
10 android.support.v4.app.Fragment.performCreateView(Fragment.java:2087)
11 android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1113)
12 android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1295)
13 android.support.v4.app.BackStackRecord.run(BackStackRecord.java:801)
14 android.support.v4.app.FragmentManagerImpl.execSingleAction(FragmentManager.java:1643)
15 android.support.v4.app.BackStackRecord.commitNowAllowingStateLoss(BackStackRecord.java:679)
16 android.support.v4.app.FragmentPagerAdapter.finishUpdate(FragmentPagerAdapter.java:143)
17 android.support.v4.view.ViewPager.populate(ViewPager.java:1272)
18 android.support.v4.view.ViewPager.populate(ViewPager.java:1120)
19 android.support.v4.view.ViewPager.onMeasure(ViewPager.java:1646)
20 android.view.View.measure(View.java:16513)
21 android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:719)
22 android.widget.RelativeLayout.onMeasure(RelativeLayout.java:455)
23 android.view.View.measure(View.java:16513)
24 android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5125)
25 android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
26 android.support.v7.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:139)
27 android.view.View.measure(View.java:16513)
28 android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5125)
29 android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1404)
30 android.widget.LinearLayout.measureVertical(LinearLayout.java:695)
31 android.widget.LinearLayout.onMeasure(LinearLayout.java:588)
32 android.view.View.measure(View.java:16513)
33 android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5125)
34 android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
35 android.view.View.measure(View.java:16513)
36 android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5125)
37 android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1404)
38 android.widget.LinearLayout.measureVertical(LinearLayout.java:695)
39 android.widget.LinearLayout.onMeasure(LinearLayout.java:588)
40 android.view.View.measure(View.java:16513)
41 android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5125)
42 android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
43 com.android.internal.policy.impl.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2300)
44 android.view.View.measure(View.java:16513)
45 android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:1955)
46 android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1152)
47 android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1334)
48 android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1039)
49 android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5653)
50 android.view.Choreographer$CallbackRecord.run(Choreographer.java:761)
51 android.view.Choreographer.doCallbacks(Choreographer.java:574)
52 android.view.Choreographer.doFrame(Choreographer.java:544)
53 android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:747)
54 android.os.Handler.handleCallback(Handler.java:733)
55 android.os.Handler.dispatchMessage(Handler.java:95)
56 android.os.Looper.loop(Looper.java:136)
57 android.app.ActivityThread.main(ActivityThread.java:5135)
58 java.lang.reflect.Method.invokeNative(Native Method)
59 java.lang.reflect.Method.invoke(Method.java:515)
60 com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:795)
61 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:611)
62 dalvik.system.NativeStart.main(Native Method)

**Comment by ghost** [comment]
Same here, 

Sony D2302 (Android 4.4.4, API 19)

Same code working fine on Nexus 5, Galaxy J3, Galaxy S5/S6

``FATAL EXCEPTION: main
                                                                       java.lang.VerifyError: se/emilsjolander/stickylistheaders/StickyListHeadersListView
                                                                           at java.lang.reflect.Constructor.constructNative(Native Method)
                                                                           at java.lang.reflect.Constructor.newInstance(Constructor.java:417)
                                                                           at android.view.LayoutInflater.createView(LayoutInflater.java:587)
                                                                           at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:687)
                                                                           at android.view.LayoutInflater.rInflate(LayoutInflater.java:746)
                                                                           at android.view.LayoutInflater.rInflate(LayoutInflater.java:749)
                                                                           at android.view.LayoutInflater.inflate(LayoutInflater.java:489)
                                                                           at android.view.LayoutInflater.inflate(LayoutInflater.java:396)
                                                                           at roneskinder.combustible.fragments.FragmentCardTransactions.onCreateView(FragmentCardTransactions.java:228)
                                                                           at android.support.v4.app.Fragment.performCreateView(Fragment.java:2080)
                                                                           at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1108)
                                                                           at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1290)
                                                                           at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1272)
                                                                           at android.support.v4.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:2149)
                                                                           at android.support.v4.app.Fragment.performActivityCreated(Fragment.java:2095)
                                                                           at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1133)
                                                                           at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1290)
                                                                           at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:801)
                                                                           at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1677)
                                                                           at android.support.v4.app.FragmentManagerImpl.executePendingTransactions(FragmentManager.java:589)
                                                                           at roneskinder.combustible.tabs.BaseContainerFragment.replaceFragment(BaseContainerFragment.java:23)
                                                                           at roneskinder.combustible.fragments.FragmentCardHolder$1$1.run(FragmentCardHolder.java:268)
                                                                           at android.os.Handler.handleCallback(Handler.java:725)
                                                                           at android.os.Handler.dispatchMessage(Handler.java:92)
                                                                           at android.os.Looper.loop(Looper.java:137)
                                                                           at android.app.ActivityThread.main(ActivityThread.java:5041)
                                                                           at java.lang.reflect.Method.invokeNative(Native Method)
                                                                           at java.lang.reflect.Method.invoke(Method.java:511)
                                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560)
                                                                           at dalvik.system.NativeStart.main(Native Method)``

**Comment by drans4775** [comment]
Pull request
