### ISSUE TITLE
in oppo x909 4.2.2 crash

### ISSUE THREAD

**Issue by hai046** [emilsjolander/StickyListHeaders#425]
phone:china oppo  x909
android version: 4.2.2 [colorOS]
crash:fast scroll to top   crash:

> 09-09 09:46:30.782  19617-19617/se.emilsjolander.stickylistheaders E/AndroidRuntime﹕ FATAL EXCEPTION: main
>     java.lang.NullPointerException
>             at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3014)
>             at android.view.View.getDisplayList(View.java:12596)
>             at android.view.View.getDisplayList(View.java:12702)
>             at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3019)
>             at android.view.View.getDisplayList(View.java:12596)
>             at android.view.View.getDisplayList(View.java:12702)
>             at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3019)
>             at android.view.View.getDisplayList(View.java:12596)
>             at android.view.View.getDisplayList(View.java:12702)
>             at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3019)
>             at android.view.View.getDisplayList(View.java:12596)
>             at android.view.View.getDisplayList(View.java:12702)
>             at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3019)
>             at android.view.View.getDisplayList(View.java:12596)
>             at android.view.View.getDisplayList(View.java:12702)
>             at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3019)
>             at android.view.View.getDisplayList(View.java:12596)
>             at android.view.View.getDisplayList(View.java:12702)
>             at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3019)
>             at android.view.View.getDisplayList(View.java:12596)
>             at android.view.View.getDisplayList(View.java:12702)
>             at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3019)
>             at android.view.View.getDisplayList(View.java:12596)
>             at android.view.View.getDisplayList(View.java:12702)
>             at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3019)
>             at android.view.View.getDisplayList(View.java:12596)
>             at android.view.View.getDisplayList(View.java:12702)
>             at android.view.HardwareRenderer$GlRenderer.draw(HardwareRenderer.java:1200)
>             at android.view.ViewRootImpl.draw(ViewRootImpl.java:2221)
>             at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2093)
>             at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1902)
>             at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1006)
>             at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:4560)
>             at android.view.Choreographer$CallbackRecord.run(Choreographer.java:749)
>             at android.view.Choreographer.doCallbacks(Choreographer.java:562)
>             at android.view.Choreographer.doFrame(Choreographer.java:532)
>             at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:735)
>             at android.os.Handler.handleCallback(Handler.java:725)
>             at android.os.Handler.dispatchMessage(Handler.java:92)
>             at android.os.Looper.loop(Looper.java:137)
>             at android.app.ActivityThread.main(ActivityThread.java:5142)
>             at java.lang.reflect.Method.invokeNative(Native Method)
>             at java.lang.reflect.Method.invoke(Method.java:511)
>             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:802)
>             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:569)
>             at dalvik.system.NativeStart.main(Native Method)

This could be the cause of colorOS  ，but i'm not sure .  Who has seen a similar phenomenon

**Comment by hai046** [comment]
i solve it by  my project 
delete code removeView(mHeader) at se.emilsjolander.stickylistheaders.StickyListHeadersListView  clearHeader() method  

>    private void clearHeader() {
>         if (mHeader != null) {
> //            removeView(mHeader);
>             mHeader = null;
>             mHeaderId = null;
>             mHeaderPosition = null;
>             mHeaderOffset = null;

```
        // reset the top clipping length
        mList.setTopClippingLength(0);
        updateHeaderVisibilities();
```

i think it cause:  removeView it call  requestLayout  but   fast scroll ，the thread async  cause null
