### ISSUE TITLE
ClassCastException: android.widget.AbsListView$LayoutParams cannot be cast to android.view.ViewGroup$MarginLayoutParams

### ISSUE THREAD

**Issue by hereisderek** [emilsjolander/StickyListHeaders#446]
`02-24 16:44:36.937 4346-4346/com.paymark.expenses E/AndroidRuntime: FATAL EXCEPTION: main
                                                                    Process: com.paymark.expenses, PID: 4346
                                                                    java.lang.ClassCastException: android.widget.AbsListView$LayoutParams cannot be cast to android.view.ViewGroup$MarginLayoutParams
                                                                        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5942)
                                                                        at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
                                                                        at se.emilsjolander.stickylistheaders.StickyListHeadersListView.onMeasure(StickyListHeadersListView.java:235)
                                                                        at android.view.View.measure(View.java:18797)
                                                                        at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:715)
                                                                        at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:461)
                                                                        at android.view.View.measure(View.java:18797)
                                                                        at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:715)
                                                                        at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:461)
                                                                        at android.view.View.measure(View.java:18797)
                                                                        at android.support.v4.view.ViewPager.onMeasure(ViewPager.java:1489)
                                                                        at android.view.View.measure(View.java:18797)
                                                                        at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:715)
                                                                        at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:461)
                                                                        at android.view.View.measure(View.java:18797)
                                                                        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5951)
                                                                        at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
                                                                        at android.view.View.measure(View.java:18797)
                                                                        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5951)
                                                                        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1465)
                                                                        at android.widget.LinearLayout.measureVertical(LinearLayout.java:748)
                                                                        at android.widget.LinearLayout.onMeasure(LinearLayout.java:630)
                                                                        at android.view.View.measure(View.java:18797)
                                                                        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5951)
                                                                        at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
                                                                        at com.android.internal.policy.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2899)
                                                                        at android.view.View.measure(View.java:18797)
                                                                        at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2100)
                                                                        at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1216)
                                                                        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1452)
                                                                        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1107)
                                                                        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6013)
                                                                        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:858)
                                                                        at android.view.Choreographer.doCallbacks(Choreographer.java:670)
                                                                        at android.view.Choreographer.doFrame(Choreographer.java:606)
                                                                        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
                                                                        at android.os.Handler.handleCallback(Handler.java:739)
                                                                        at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                        at android.os.Looper.loop(Looper.java:148)
                                                                        at android.app.ActivityThread.main(ActivityThread.java:5466)
                                                                        at java.lang.reflect.Method.invoke(Native Method)
                                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
                                                                        at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:114)`

**Comment by HaileApp** [comment]
Instead of using the generic ViewGroup in your getView,just use the AbsListView to make it more specific and executing the working code
