### ISSUE TITLE
Android O Beta -  java.lang.IllegalStateException: Handling non empty state of parent class is not implemented

### ISSUE THREAD

**Issue by NLLAPPS** [emilsjolander/StickyListHeaders#477]
Is this project still maintained?
Every now and then I get above error on Android O Beta. I guess it is related the OS but just heads up

Stack trace:

Java.lang.IllegalStateException: Handling non empty state of parent class is not implemented
at se.emilsjolander.stickylistheaders.StickyListHeadersListView.onSaveInstanceState(StickyListHeadersListView.java:1098)
at android.view.View.dispatchSaveInstanceState(View.java:17157)
at android.view.ViewGroup.dispatchSaveInstanceState(ViewGroup.java:3668)
at android.view.ViewGroup.dispatchSaveInstanceState(ViewGroup.java:3674)
at android.view.ViewGroup.dispatchSaveInstanceState(ViewGroup.java:3674)
at android.view.View.saveHierarchyState(View.java:17140)

**Comment by sandy-8925** [comment]
I can confirm, this error happens only on Android O for us, and seems to happen only on Nexus/Pixel devices.

Edit: Was mislead by API level 25 in crash reports, looks like Android O reported API level 25 for a while.

**Comment by NLLAPPS** [comment]
As far as I know it only happens on Android O. It might be a bug with the platform

**Comment by mtotschnig** [comment]
With O and maybe earlier, the assumption that StickyListHeaderListView class relies on (that the super class does not have any state of its own to safe) no longer necessarily holds true. On my fork I tried to implement proper handling of this new situation: https://github.com/mtotschnig/StickyListHeaders/commit/c9f9a44cb689320fa2e22496460a83264d1b3020

**Comment by chrisonline** [comment]
@mtotschnig Great, thanks. Do you have a compile url for gradle for your fork?
Because this library seems is discontinued and won't get any fix.

**Comment by mtotschnig** [comment]
@chrisonline Yes it can be included via Jitpack: https://jitpack.io/#mtotschnig/StickyListHeaders/master-SNAPSHOT

**Comment by mschrod** [comment]
@mtotschnig thanks for this

**Comment by NLLAPPS** [comment]
@mtotschnig There might be an issue with your implementation. I had a crash in the app, unrelated to your code but trace kept showing me your implementation about saved state. I was not able to capture it. 
I will post details if I can recreate it

**Comment by NLLAPPS** [comment]
Ah! Error exactly as @nvquockhtn posted at https://github.com/mtotschnig/StickyListHeaders/commit/c9f9a44cb689320fa2e22496460a83264d1b3020

**Comment by Cylix** [comment]
I got this issue from crashlytics too (`Java.lang.IllegalStateException: Handling non empty state of parent class is not implemented`).

Did you find a way to reproduce it?
I setup Android O on a virtual device on Android Studio (nexus pixel xl) but everything works fine.
If it happens in the onSaveInstance, I expect it to happen on some configuration change, but no way to reproduce it  (I tried to rotate, lock, switch from one app to another, whatever, everything works fine).

I'd like to at least be able to reproduce it so that I can be sure that the fix works.
So, if you have any clue about how to trigger the exception, I'd be suuuuper glad!

**Comment by sandy-8925** [comment]
I was able to reproduce on actual physical device (Nexus 6P with Android O)
when launching a different activity from the activity containing
StickyListHeadersListView in it's view hierarchy.

**Comment by NLLAPPS** [comment]
I was not able to reproduce it on Nexus 5x with latest Android beta but got many crash reports from Nexus 6P when launching a different activity from the activity with StickyHeaders. I wonder if it is related to device.

**Comment by Sloy** [comment]
I didn't reproduce it with a virtual device either. But with a physical Nexus 6P it happened all the time.

**Comment by Cylix** [comment]
Thanks for your replies!
Yeah, unfortunately, I do not have nexus 6P or pixel, only a Nexus 6 but there is no way to install Android O on it apparently, so I guess I have no way, for now, to reproduce on my side.
Thank again for the quick replies :)

**Comment by mtotschnig** [comment]
By the way, you can increase the probability of reproducing the crash by setting "Don't keep activities" in the systems' developer settings.

**Comment by crucibond** [comment]
Hi, I am facing similar issue and were anyone able to solve this?


java.lang.IllegalStateException: 
  at se.emilsjolander.stickylistheaders.StickyListHeadersListView.onSaveInstanceState (StickyListHeadersListView.java:1029)

**Comment by mtotschnig** [comment]
It is solved in https://github.com/mtotschnig/StickyListHeaders/releases/tag/2.7.1 .
Use it via Jitpack
`compile 'com.github.mtotschnig:StickyListHeaders:2.7.1'`

**Comment by crucibond** [comment]
There seems to be an issue with the release. I used both git pack and normal dependency as in "    compile 'se.emilsjolander:stickylistheaders:x.x.x" Both doesn't seem to find 2.7.1. This is strange.

**Comment by madhacked** [comment]
@emilsjolander any plans to bring in @mtotschnig fixes? I'd prefer not to add Jitpack to my project! Thanks!

**Comment by Cylix** [comment]
@madhacked this project is 100% not maintained anymore, the last commit is dated from 2015. I don't think you should expect any plans.
Best case would be someone forking this repo and maintaining the fork.

**Comment by edisonw** [comment]
fyi @madhacked and those who do not want to use jitpack or the additional support library dependency:

I have compiled the aar off master + 1 proper fix commit (https://github.com/edisonw/StickyListHeaders/commit/3dd88a2ad789ec24f369be35a8494ccf9379a07e)

The download link is here: 

https://github.com/edisonw/StickyListHeaders/blob/master/release-2.7.2.aar

Everyone feel free to rename and download it locally if needed.

Note the correct way to use an aar file, if your file is inside /projectRoot/app/libs/sticky-list-headers.aar, 

You need to declare this in your root dependency configuration: 
```

        flatDir {
            dirs project(':app').file('libs')
        }

```

And then you can use it as 
`
    compile(name:'sticky-list-headers', ext:'aar')
`

**Comment by jungc** [comment]
Hey guys, 

@mtotschnig's personal forks had changes other than the problem addressed above.
I've created a fork with his solution to the problem without any other changes.
PR: https://github.com/jungc/StickyListHeaders/pull/1
It has been merged to master on my fork
Also, I changed the version number to "2.7.1-FORK" in case this project ever gets maintained again.

Where to get the .aar file for your project :)
https://github.com/jungc/StickyListHeaders/releases/tag/2.7.1-FORK

**NOTE:** 
**1. This change comes from Groupon.**
**2. We won't maintain it.**

**Comment by haemi** [comment]
@jungc how can I install/use this fork?

**Comment by dapda** [comment]
Mute

Vào 11-10-2017 07:34, "Jaden Choi" <notifications@github.com> đã viết:

**Comment by jungc** [comment]
@haemi thanks for pointing that out. I've uploaded the .aar file here https://github.com/jungc/StickyListHeaders/releases/tag/2.7.1-FORK

**Comment by haemi** [comment]
@jungc thanks, I did that but I get `failed to resolve: se.emilsjolander:stickylistheaders:stickylistheaders`:

I updated my app-build.gradle:

```
repositories {
    maven { url "${rootDir}/local_repos" }
    jcenter()
    maven { url 'https://maven.fabric.io/public' }
    google()
}
```

```
implementation "se.emilsjolander:stickylistheaders:stickylistheaders:2.7.1-FORK@aar"
```

file is here:

```
local_repos/se/emilsjolander/stickylistheaders/2.7.1-FORK/stickylistheaders-2.7.1-FORK.aar
```

**Comment by haemi** [comment]
@jungc help pleeeeease...

**Comment by jungc** [comment]
@haemi @Sloy sorry about the delay. It looks like I made a typo with the previous release draft. It took me awhile to notice but it should be:
`implementation "se.emilsjolander:stickylistheaders:2.7.1-FORK@aar"` :)
`<group id>:<artifact id>:<version>@aar`^

**Comment by brianguertin** [comment]
Hey guys, you don't have to use a fork; the extra saved state comes from the autofill framework.

Disable autofill on the `StickyListHeadersListView`, and it will work fine.

```java
if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
  myList.setImportantForAutofill(IMPORTANT_FOR_AUTOFILL_NO_EXCLUDE_DESCENDANTS);
}
```

Of course, if you WANT autofill in your list view, then this workaround is not for you :)

**Comment by golubov-csaba-antal** [comment]
@brianguertin thanks, it's working perfectly!

**Comment by ykphuah** [comment]
@brianguertin Thanks, it works. Strange that I have two list with sticky headers and this issue only happen to one of them. I tried to compare the two and they seems exactly the same. Only one of them need your "fix". 

Thanks again!

**Comment by prince3156** [comment]
Android 25 the same issue occured.

**Comment by kohterachai** [comment]
#420 Xposed v89 SDK26 crash on module download page

**Comment by kohterachai** [comment]
@NLLAPPS

_Sent from my A37f using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Horia22** [comment]
I am extending StickyListHeadersListView:

```
public class CustomStickyListHeadersListView extends StickyListHeadersListView {
....
    @Override
    public void setImportantForAutofill(int mode) {
       if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
            super.setImportantForAutofill(IMPORTANT_FOR_AUTOFILL_NO_EXCLUDE_DESCENDANTS);
       }
    }
....
}
```

this does not work for me, still crashing...

**Comment by peshkira** [comment]
@HoriaGoran Do you call your method then? You have just overriden it, but you probably never call it?

**Comment by Horia22** [comment]
I did call it.
If you look at the View.java, onSaveInstanceState() it has this condition:

   if (mStartActivityRequestWho != null || isAutofilled()
                || mAutofillViewId > LAST_APP_AUTOFILL_ID) {

So even if isAutofilled() will be false with the proposed fix, its is enough for 1 of the other 2 checks to be true and to return a non empty state for the exception to be thrown.
I think this is the reason why the fix with setImportantForAutofill didn't work in my case.
I fixed this by importing one of the forked libs mentioned in the thread.

**Comment by SolveBugs** [comment]
@brianguertin Excuse me, can say in detail how to use the code you have shown above,thanks a lot.

**Comment by SolveBugs** [comment]
@brianguertin I have already solved, thanks again。

**Comment by hendrawd** [comment]
autofill framework breaks everything :(

**Comment by hendrawd** [comment]
@mtotschnig I tried your solution, but there is an error when running the app.
`Program type already present: se.emilsjolander.stickylistheaders.CheckableWrapperView`
Do you know how to fix it except disabling R8 and D8?

**Comment by hendrawd** [comment]
Looks like, one of my modules also using this library, so I had to change both of my module-level build.gradle and app-level build.gradle, clean and rebuild to make it work.

**Comment by gigabitese** [comment]
colleagues that same error happens in android 9 I get the same error when debugging java.lang.IllegalStateException: Handling non-empty state of parent class is not implemented !! help !!

**Comment by NiranjanaSekar** [comment]
any alternative or fix for this?. Issue is when editing search view and set text works on marshmallow, not working in pie. 

Failed to resolve: se.emilsjolander:stickylistheaders:2.7.1

**Comment by damionx7** [comment]
Duplicate of  #483

**Comment by sarithnob** [comment]
This case is seen on crashlytics for me too. But it happened on Android 12, Pixel 4 XL and Pixel 3 XL. Anyways, I can't reproduce the crash on Emulator of the same device's model and OS.

**Comment by 440791217** [comment]
收到

**Comment by CL-window** [comment]
Hello，我已收到邮件，待我仔细阅读后再回复。

**Comment by trifagabriel** [comment]
I was able to solve this by setting .setSaveEnabled(false) on the agenda list view

**Comment by thinkmobilede** [comment]
> I was able to solve this by setting .setSaveEnabled(false) on the agenda list view

actually this solved the issue for me in Android 15 while setImportantForAutofill did not.

**Comment by CL-window** [comment]
Hello，我已收到邮件，待我仔细阅读后再回复。

**Comment by 440791217** [comment]
收到
