### ISSUE TITLE
Crash on Android O

### ISSUE THREAD

**Issue by rohitsharma181589** [emilsjolander/StickyListHeaders#483]
Hi

I am getting crash every time :
Log :
02-12 10:25:24.715 12455-12455/com.medicbleep.chat E/AndroidRuntime: FATAL EXCEPTION: main
                                                                     Process: com.medicbleep.chat, PID: 12455
                                                                     java.lang.IllegalStateException: Handling non empty state of parent class is not implemented
                                                                         at se.emilsjolander.stickylistheaders.StickyListHeadersListView.onSaveInstanceState(StickyListHeadersListView.java:1098)
                                                                         at android.view.View.dispatchSaveInstanceState(View.java:17652)
                                                                         at android.view.ViewGroup.dispatchSaveInstanceState(ViewGroup.java:3702)
                                                                         at android.view.ViewGroup.dispatchSaveInstanceState(ViewGroup.java:3708)
                                                                         at android.view.ViewGroup.dispatchSaveInstanceState(ViewGroup.java:3708)
                                                                         at android.view.ViewGroup.dispatchSaveInstanceState(ViewGroup.java:3708)
                                                                         at android.view.ViewGroup.dispatchSaveInstanceState(ViewGroup.java:3708)
                                                                         at android.view.View.saveHierarchyState(View.java:17635)
                                                                         at com.android.internal.policy.PhoneWindow.saveHierarchyState(PhoneWindow.java:2133)
                                                                         at android.app.Activity.onSaveInstanceState(Activity.java:1579)
                                                                         at android.support.v4.app.SupportActivity.onSaveInstanceState(SupportActivity.java:74)
                                                                         at android.support.v4.app.FragmentActivity.onSaveInstanceState(FragmentActivity.java:538)
                                                                         at android.support.v7.app.AppCompatActivity.onSaveInstanceState(AppCompatActivity.java:509)
                                                                         at android.app.Activity.performSaveInstanceState(Activity.java:1509)
                                                                         at android.app.Instrumentation.callActivityOnSaveInstanceState(Instrumentation.java:1507)
                                                                         at android.app.ActivityThread.callCallActivityOnSaveInstanceState(ActivityThread.java:4980)
                                                                         at android.app.ActivityThread.performStopActivityInner(ActivityThread.java:4278)
                                                                         at android.app.ActivityThread.handleStopActivity(ActivityThread.java:4344)
                                                                         at android.app.ActivityThread.-wrap24(Unknown Source:0)
                                                                         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1722)
                                                                         at android.os.Handler.dispatchMessage(Handler.java:105)
                                                                         at android.os.Looper.loop(Looper.java:164)
                                                                         at android.app.ActivityThread.main(ActivityThread.java:6809)
                                                                         at java.lang.reflect.Method.invoke(Native Method)
                                                                         at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)

Please update the same with the fix provided by : https://github.com/mtotschnig/StickyListHeaders/commit/c9f9a44cb689320fa2e22496460a83264d1b3020

**Comment by achinverma** [comment]
I am facing the same issue, any solution?

**Comment by anthonyY** [comment]
me too, how to fixed it ?

**Comment by abhishek592001** [comment]
try to set in xml 
android:saveEnabled="false"

Its working after adding saveEnabled"false"

<se.emilsjolander.stickylistheaders.StickyListHeadersListView
            android:id="@+id/list" android:saveEnabled="false"
            android:layout_below="@+id/appbar"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:dividerHeight="0dp"/>

**Comment by prateekyaad** [comment]
> try to set in xml
> android:saveEnabled="false"
> 
> Its working after adding saveEnabled"false"
> 
> <se.emilsjolander.stickylistheaders.StickyListHeadersListView
> android:id="@+id/list" android:saveEnabled="false"
> android:layout_below="@+id/appbar"
> android:layout_width="match_parent"
> android:layout_height="match_parent"
> android:dividerHeight="0dp"/>

Thanks it worked saved my day

**Comment by trifagabriel** [comment]
@abhishek592001 DUDE THANK YOU!!!!! i've been look for a solution to this problem for more than 2 days now, and this solve it. Thanks!!!!!!!!!!!!!!!
