### ISSUE TITLE
Crash on scrolling  listview java.lang.ArrayIndexOutOfBoundsException: 

### ISSUE THREAD

**Issue by rahulsmart** [emilsjolander/StickyListHeaders#486]
While Scrolling up and down it throws this exceptions, Where I might be doing wrong??

Just taken the code from sample example...

java.lang.ArrayIndexOutOfBoundsException: length=2; index=14
at android.widget.AbsListView$RecycleBin.addScrapView(AbsListView.java:6671)
at android.widget.AbsListView.trackMotionScroll(AbsListView.java:5024)
at android.widget.AbsListView.scrollIfNeeded(AbsListView.java:3448)
at android.widget.AbsListView.onTouchMove(AbsListView.java:3844)
at android.widget.AbsListView.onTouchEvent(AbsListView.java:3675)
at android.view.View.dispatchTouchEvent(View.java:9307)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2548)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2241)
at se.emilsjolander.stickylistheaders.StickyListHeadersListView.dispatchTouchEvent(StickyListHeadersListView.java:483)
 at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2554)
 at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2255)
 at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2554)
 at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2255)
 at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2554)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2255)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2554)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2255)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2554)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2255)
 at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2554)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2255)
at com.android.internal.policy.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2403)
at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1737)
 at android.app.Activity.dispatchTouchEvent(Activity.java:2843)
at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:71)
at com.android.internal.policy.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2364)
 at android.view.View.dispatchPointerEvent(View.java:9527)
at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4248)
at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4101)
at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3647)
at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3700)
at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3666)
 at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3792)
at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3674)
at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3849)
at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3647)
at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3700)
at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3666)
at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3674)
at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3647)
at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:5944)
at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:5918)
at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:5879)
at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6047)
at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
at android.view.InputEventReceiver.nativeConsumeBatchedInputEvents(Native Method)
at android.view.InputEventReceiver.consumeBatchedInputEvents(InputEventReceiver.java:176)
at android.view.ViewRootImpl.doConsumeBatchedInput(ViewRootImpl.java:6018)
at android.view.ViewRootImpl$ConsumeBatchedInputRunnable.run(ViewRootImpl.java:6070)
at android.view.Choreographer$CallbackRecord.run(Choreographer.java:858)
at android.view.Choreographer.doCallbacks(Choreographer.java:670)

**Comment by oscardo** [comment]
Hi my friends https://stackoverflow.com/questions/30365062/out-of-bounds-exception-for-list-view-with-multiple-view-types help you! thk
