### ISSUE TITLE
Android P - App crashing  - Invalid Region.Op - only INTERSECT and DIFFERENCE are allowed

### ISSUE THREAD

**Issue by pravingaikwad07** [emilsjolander/StickyListHeaders#493]
App is crashing in Android P when I try to expand an item from the sticky headerlist.

Error Logcat:
java.lang.IllegalArgumentException: Invalid Region.Op - only INTERSECT and DIFFERENCE are allowed
        at android.graphics.Canvas.checkValidClipOp(Canvas.java:779)
        at android.graphics.Canvas.clipPath(Canvas.java:1007)
        at co.lujun.androidtagview.TagView.drawRipple(TagView.java:375)
        at co.lujun.androidtagview.TagView.onDraw(TagView.java:214)
        at android.view.View.draw(View.java:20366)
        at android.view.View.updateDisplayListIfDirty(View.java:19241)
        at android.view.View.draw(View.java:20094)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4337)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4116)
        at android.view.View.draw(View.java:20369)
        at android.view.View.updateDisplayListIfDirty(View.java:19241)
        at android.view.View.draw(View.java:20094)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4337)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4116)
        at android.support.constraint.ConstraintLayout.dispatchDraw(ConstraintLayout.java:2023)
        at android.view.View.draw(View.java:20369)
        at android.view.View.updateDisplayListIfDirty(View.java:19241)
        at android.view.View.draw(View.java:20094)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4337)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4116)
        at android.view.View.updateDisplayListIfDirty(View.java:19232)
        at android.view.View.draw(View.java:20094)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4337)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4116)
        at se.emilsjolander.stickylistheaders.WrapperView.dispatchDraw(WrapperView.java:145)
        at android.view.View.updateDisplayListIfDirty(View.java:19232)
        at android.view.View.draw(View.java:20094)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4337)
        at android.widget.ListView.drawChild(ListView.java:3664)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4116)
        at android.widget.AbsListView.dispatchDraw(AbsListView.java:2681)
        at android.widget.ListView.dispatchDraw(ListView.java:3659)
        at se.emilsjolander.stickylistheaders.WrapperViewList.dispatchDraw(WrapperViewList.java:105)
        at android.view.View.draw(View.java:20369)
        at android.widget.AbsListView.draw(AbsListView.java:4402)
        at android.view.View.updateDisplayListIfDirty(View.java:19241)
        at android.view.View.draw(View.java:20094)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4337)
        at se.emilsjolander.stickylistheaders.StickyListHeadersListView.dispatchDraw(StickyListHeadersListView.java:281)
        at android.view.View.updateDisplayListIfDirty(View.java:19232)
        at android.view.View.draw(View.java:20094)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4337)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4116)
        at android.view.View.updateDisplayListIfDirty(View.java:19232)
        at android.view.View.draw(View.java:20094)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4337)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4116)
        at android.view.View.updateDisplayListIfDirty(View.java:19232)
        at android.view.View.draw(View.java:20094)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4337)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4116)
        at android.view.View.updateDisplayListIfDirty(View.java:19232)
        at android.view.View.draw(View.java:20094)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4337)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4116)
        at android.view.View.updateDisplayListIfDirty(View.java:19232)
        at android.view.View.draw(View.java:20094)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4337)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4116)
        at android.view.View.updateDisplayListIfDirty(View.java:19232)
        at android.view.View.draw(View.java:20094)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4337)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4116)
        at android.view.View.draw(View.java:20369)
        at com.android.internal.policy.DecorView.draw(DecorView.java:781)

E/AndroidRuntime:     at android.view.View.updateDisplayListIfDirty(View.java:19241)
        at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:690)
        at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:696)
        at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:805)
        at android.view.ViewRootImpl.draw(ViewRootImpl.java:3515)
        at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:3312)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2681)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1633)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7786)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1004)
        at android.view.Choreographer.doCallbacks(Choreographer.java:816)
        at android.view.Choreographer.doFrame(Choreographer.java:751)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:990)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6863)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:537)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

**Comment by DerekApax** [comment]
I had this problem because of a custom subview on the list cells. In my case a "MaterialSwitch" was trying to render a shadow outside of the cell bounds. Try hiding all the custom subviews on your cells to see if this is the cause of the problem. The sample project does not experience this problem, so make close comparison.

**Comment by mahadeomali** [comment]
Thanks

**Comment by Nasir-ceh** [comment]
Hi,
you just need to remove :
**`.setCropShape(CropImageView.CropShape.OVAL)`**

**Comment by SwatiL** [comment]
Error Logcat:
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.xposure.globalhubs, PID: 26870
    java.lang.IllegalArgumentException: Invalid Region.Op - only INTERSECT and DIFFERENCE are allowed
        at android.graphics.Canvas.checkValidClipOp(Canvas.java:791)
        at android.graphics.Canvas.clipPath(Canvas.java:1019)
        at co.ceryle.radiorealbutton.RoundedCornerLayout.dispatchDraw(RoundedCornerLayout.java:80)
        at android.view.View.buildDrawingCacheImpl(View.java:19613)
        at android.view.View.buildDrawingCache(View.java:19479)
        at android.view.View.draw(View.java:20068)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4379)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4152)
        at android.view.View.draw(View.java:20375)
        at android.view.View.updateDisplayListIfDirty(View.java:19223)
        at android.view.View.draw(View.java:20076)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4379)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4152)
        at android.view.View.updateDisplayListIfDirty(View.java:19214)
        at android.view.View.draw(View.java:20076)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4379)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4152)
        at android.view.View.updateDisplayListIfDirty(View.java:19214)
        at android.view.View.draw(View.java:20076)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4379)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4152)
        at android.view.View.updateDisplayListIfDirty(View.java:19214)
        at android.view.View.draw(View.java:20076)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4379)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4152)
        at android.view.View.updateDisplayListIfDirty(View.java:19214)
        at android.view.View.draw(View.java:20076)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4379)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4152)
        at android.view.View.updateDisplayListIfDirty(View.java:19214)
        at android.view.View.draw(View.java:20076)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4379)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4152)
        at android.view.View.draw(View.java:20375)
        at com.android.internal.policy.DecorView.draw(DecorView.java:1239)
        at android.view.View.updateDisplayListIfDirty(View.java:19223)
        at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:686)
        at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:692)
        at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:801)
        at android.view.ViewRootImpl.draw(ViewRootImpl.java:3399)
        at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:3192)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2561)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1514)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7387)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1063)
        at android.view.Choreographer.doCallbacks(Choreographer.java:875)
        at android.view.Choreographer.doFrame(Choreographer.java:807)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1049)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:224)
        at android.app.ActivityThread.main(ActivityThread.java:7104)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:876)
