### ISSUE TITLE
Not compatible with Android 10

### ISSUE THREAD

**Issue by alixwar** [emilsjolander/StickyListHeaders#504]
Version used of library: 2.7.0
Android Gradle version: 3.5.0

App crashes when targetting API 29:

2019-09-04 14:20:37.302 17366-17366/XXX: Accessing hidden field Landroid/widget/AbsListView;->mSelectorRect:Landroid/graphics/Rect; (greylist-max-p, reflection, denied)
2019-09-04 14:20:37.303 17366-17366/XXX W/System.err: java.lang.NoSuchFieldException: No field mSelectorRect in class Landroid/widget/AbsListView; (declaration of 'android.widget.AbsListView' appears in /system/framework/framework.jar!classes3.dex)
2019-09-04 14:20:37.303 17366-17366/XXX W/System.err:     at java.lang.Class.getDeclaredField(Native Method)
2019-09-04 14:20:37.303 17366-17366/XXX W/System.err:     at se.emilsjolander.stickylistheaders.WrapperViewList.<init>(WrapperViewList.java:35)
2019-09-04 14:20:37.303 17366-17366/XXX W/System.err:     at se.emilsjolander.stickylistheaders.StickyListHeadersListView.<init>(StickyListHeadersListView.java:129)

**Comment by nguyencan** [comment]
I got the same issue. In my case, it's not crashed but I always get that log. Anyone can resolve this?

**Comment by shylendramadda** [comment]
Same issue here, any update on this?

**Comment by alixwar** [comment]
> Same issue here, any update on this?

You may want to look into an Android native solution using RecyclerView nowadays. At least that's what I did.

**Comment by shylendramadda** [comment]
Okay thanks, just want to know if there is any quick fix.

**Comment by shylendramadda** [comment]
> > Same issue here, any update on this?
> 
> You may want to look into an Android native solution using RecyclerView nowadays. At least that's what I did.

Okay thanks, just want to know if there is any quick fix.
